language: node_js
node_js:
    - "8.2.1"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - ng test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start